import { SystemSettings } from './useSystemSettingsLazy';

const mockSettings: SystemSettings = {
  id: 'local-settings',
  smtp_host: 'smtp.gmail.com',
  smtp_port: '587',
  smtp_secure: 'TLS',
  smtp_username: '',
  smtp_password: '',
  smtp_from_email: 'noreply@its.ms.gov',
  smtp_from_name: 'Mississippi ITS Certificate Monitor',
  email_smtp_api_key: '',
  smtp_api_url: 'http://localhost:5000',
  alert_email: 'admin@its.ms.gov',
  enable_notifications: true,
  enable_sms_notifications: false,
  phone_number: '',
  enable_slack_integration: false,
  slack_webhook_url: '',
  slack_channel_name: '#certificate-alerts',
  enable_telegram_bot: false,
  email_critical_alerts: true,
  email_warning_alerts: true,
  email_informational: false,
  sms_critical_alerts: true,
  sms_warning_alerts: false,
  sms_informational: false,
  slack_critical_alerts: true,
  slack_warning_alerts: true,
  slack_informational: false,
  sms_gateway_url: '',
  sms_gateway_login: '',
  sms_gateway_password: '',
  ssl_alert_threshold_days: 30,
  ssl_warning_threshold_days: 7,
  ssl_check_frequency: 'daily',
  ssl_email_notifications: true,
  ssl_sms_notifications: false,
  ssl_notification_frequency: 'immediate',
  ssl_reminder_enabled: true,
  ssl_reminder_days_before: 3,
  ssl_auto_renewal_enabled: false,
  ssl_auto_renewal_days_before: 14,
};

export const useSystemSettings = () => ({
  settings: mockSettings,
  loading: false,
  updateSettings: async (_: Partial<SystemSettings>) => {},
  saveSettings: async () => {},
});
